name: Installing Neuvector
on:
  push
jobs:
  install-neuvector:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install NeuVector
        uses: ./
        with:
          Version: "5.4.2"
